services:
  foxglove-bridge:
    # image: husarion/foxglove-bridge:humble-0.7.2-20231013
    build:
      dockerfile: Dockerfile
      context: ../
    ports:
      - 8766:8766
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8766

  foxglove:
    image: husarion/foxglove:1.72.0
    ports:
      - 9090:9090
    volumes:
      - ./foxglove_layout.json:/foxglove/default-layout.json
    environment:
      - DS_TYPE=foxglove-websocket
      - DS_PORT=8766
      - UI_PORT=9090
